version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: falcon-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: falcon_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: falcon-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      # A string de conexão do Prisma aponta para o serviço 'db' usando as variáveis acima
      - DATABASE_URL=postgresql://admin:password123@db:5432/falcon_db?schema=public
      # Configurações do NextAuth para funcionar via Docker
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=super_secret_key_123_mudar_em_prod
    depends_on:
      - db
